#!/bin/sh
set -e
rm .coverage
nc='\033[0m'
lblue='\033[1;34m';
lgreen='\033[1;32m';
lgray='\033[1;37m';
echo "${lgray}[Building PFS]${nc}"
echo ""
echo "${lblue}[Running test_db.py]${nc}"
python-coverage -x test_db.py
echo "${lblue}[Running test_statement.py]${nc}"
python-coverage -x test_statement.py
echo "${lgreen}[All tests passed]${nc}"
echo ""
echo "${lgray}[Coverage Report]${nc}"
python-coverage -rm -o /usr
